### ISSUE TITLE
make writer to a trait?

### ISSUE THREAD

**Issue by huangjj27** [rust-cli/env_logger#149]
As I'm trying to add wasm logger, it needs a totally different implement for `Writer` and `Buffer`, I think we need to make `Writer` be a trait so that it could be more extensive

**Comment by epage** [comment]
Did #204 take care of this for you?

**Comment by huangjj27** [comment]
> Did https://github.com/rust-cli/env_logger/pull/204 take care of this for you?

@epage It's good enough! Thanks for notification. I will dig in it later.
