### ISSUE TITLE
Split Filter and Builder into separate crate

### ISSUE THREAD

**Issue by vadixidav** [rust-cli/env_logger#193]
I am finding the `Filter` to be useful for creating my own logger in a custom wasm environment. This functionality is useful, but to pull it in I also have to pull in the whole `env_logger` crate. The readme for this crate reads that it should only be used for binaries, which makes sense, but this one component of it is useful for making libraries. Is it possible that the `Filter` and `Builder` can be split into their own crate? It seems like a good thing to refactor out. Essentially, the whole `filter` module.

**Comment by jplatte** [comment]
I think this has been brought up somewhere before. CC @KodrAus who knows a lot more about the overall log ecosystem than me.
