### ISSUE TITLE
No color on Windows when using builder

### ISSUE THREAD

**Issue by roman-khazanskii** [rust-cli/env_logger#225]
If I just do `env_logger::init();` then I see colored log messages, as expected, with different color for every log leve.

However, if I use builder - everything is colorless, even though I call ` .write_style(WriteStyle::Always)`:

``` rust
    env_logger::builder()
        .format(|buf, record| {
            writeln!(
                buf,
                "{} [{}] - {}",
                Local::now().format("%Y-%m-%d %H:%M:%S"),
                record.level(),
                record.args()
            )
        })
        .write_style(WriteStyle::Always)
        .filter(Some(botname), LevelFilter::Info)
        .init();
```

However, if I manually color all the text, like this:

``` rust
    env_logger::builder()
        .format(|buf, record| {

            let mut style = buf.style();

            style.set_color(Color::Red);

            writeln!(
                buf,
                "{} [{}] - {}",
                Local::now().format("%Y-%m-%d %H:%M:%S"),
                record.level(),
                style.value(record.args())
            )
        })
        .filter(Some(botname), LevelFilter::Info)
        .write_style(WriteStyle::Always)
        .init();
```

red text is printed. Does it mean that if I want to use builder, I have to manually color all different levels?

**Comment by relaxcn** [comment]
Me too. Does anyone have any idea?

**Comment by relaxcn** [comment]
It would be better if you could set the time zone

**Comment by lmapii** [comment]
Stumbled upon the same topic. Once you overwrite `. format` you essentially use all the styling options and most of the builder calls won't do any good anymore. Same holds for `pretty_env_logger`. The fact that the `format: fmt::Builder` member of the `Builder` is private makes all additional builder calls obsolete. It would be great to have access to `format` within the closure?

**Comment by Timmmm** [comment]
I have this problem even without `format()`. I have this code for tests:

```
    let _ = env_logger::builder().filter_level(log::LevelFilter::Info).write_style(env_logger::WriteStyle::Always).is_test(true).try_init();
    error!("Error!!");
```

No colour on Windows (haven't tried other platforms).

**Comment by Timmmm** [comment]
Ah actually in my case it was `is_test(true)` that was causing the lack of colour. Without that I get colour. Not exactly sure why it would do that but never mind.

**Comment by epage** [comment]
#298 will switch us to `anstream` and allow `WriteStyle` to control `is_test` output
