### ISSUE TITLE
atty advisory issued

### ISSUE THREAD

**Issue by ckoehler** [rust-cli/env_logger#247]
See https://rustsec.org/advisories/RUSTSEC-2021-0145

**Comment by willbuckner** [comment]
To add one bit of additional context; atty is unmaintained, so this dependency probably needs to be completely replaced.

**Comment by rnestler** [comment]
I guess this can be closed, since the current env_logger version uses `is-terminal`.

**Comment by epage** [comment]
Missed this issue, thanks!
