### ISSUE TITLE
How to forcibly color output even when the output is not a terminal?

### ISSUE THREAD

**Issue by your-diary** [rust-cli/env_logger#258]
Many UNIX commands have the option `--color {auto|always|never}`, and `--color always` always outputs colored result even when the destination is not a terminal.

In a similar manner, in `env_logger`, how to forcibly color output even when the output is not a terminal? In other words, I'd like to optionally disable terminal detection.

**Comment by miraclx** [comment]
```rust
fn main() {
    env_logger::builder()
        .write_style(WriteStyle::Always)
        .init();
}
```

or

```console
RUST_LOG_STYLE=always ./app
```

**Comment by your-diary** [comment]
@miraclx 
Both worked like a charm. Thank you.
