### ISSUE TITLE
Is this library thread-safe?

### ISSUE THREAD

**Issue by your-diary** [rust-cli/env_logger#269]
Is this library thread-safe?

[`README.md`](https://github.com/rust-cli/env_logger/blob/main/README.md) and [the official documentation](https://docs.rs/env_logger/latest/env_logger/) say nothing about that.

Is this code safe?
```rust
use log::error;
use std::thread;

fn main() {
    env_logger::init();

    let handle = thread::spawn(|| {
        error!("hello");
    });

    error!("world");

    handle.join().unwrap();
}
```

**Comment by matthiasbeyer** [comment]
What exactly do you mean by "thread safe"?

It won't print `hewollrlod`, but it will either print "hello\nworld" or "world\nhello"!

**Comment by your-diary** [comment]
@matthiasbeyer 

>  What exactly do you mean by "thread safe"?

I wanted to mean "can this library print `hewollrlod`"?

> It won't print `hewollrlod`

Is this behavior guaranteed? If so, to confirm it, do I have to read the source code? Or is it written in some documentation?

**Comment by epage** [comment]
Maybe its a bias of mine but that would be expected within the Rust ecosystem. Just like `println!` will not interleave text (but multiple `println`s will), a logged event should not be interleaved.

**Comment by your-diary** [comment]
@epage 

As far as I understand, `println!()` is thread-safe because it always locks and unlocks `/dev/stdout` ([unofficial source](https://www.reddit.com/r/rust/comments/5puyx2/comment/dcua5g5/?utm_source=share&utm_medium=web2x&context=3)).

So I think it is *possible* this library avoids `println!()` family to improve performance because locking / unlocking is relatively slow. Such an implementation is clearly problematic in using multi-threaded context, but safe in single-threaded context.

**Comment by epage** [comment]
`std` only exposes `stdout` / `stderr` with locking.  This is independent of the `println` macro..  You can explicitly acquire the lock to be able to make multiple calls, but there is always a lock.  You'd need to pull in something like `libc` to do output without a lock which is enough off the beaten path that it isn't a general assumption when working within Rust code.

The bigger risk is making multiple calls to `stdout` / `stderr` without grabbing the lock.  This is both slower (multiple aquire/releases) and can lead to interleaved output.

And to get back to my point, the general expectation within the Rust community is that `println` and `println`-like macros, like the `log` macros, will not interleave.
