### ISSUE TITLE
about doc

### ISSUE THREAD

**Issue by wiiznokes** [rust-cli/env_logger#281]
Hello, thank you for this great crate. I just want to point out that there is no example to show that you can configure multiple crates in a row with a comma:
```
RUST_LOG = "data=debug,hardware=debug"
```

Also, I lost a lot of time because I had a crate called fan-control, and the correct name to configure it was fan_control, I think it would be good to mention it in the docs.

Thanks

**Comment by epage** [comment]
Technically we do describe this syntax

>  The value of this environment variable is a comma-separated list of logging directives.

but that is easy to miss and showing it in the syntax, maybe with an example, could help.

**Comment by epage** [comment]
Oh, looks like we do have examples at the end of the section.   Making tweaks to hopefully catch people's eye more.
