### ISSUE TITLE
Cargo.lock is not meant to be checked in for libraries

### ISSUE THREAD

**Issue by SpamapS** [rust-cli/env_logger#284]
Hi! Perhaps thinking has evolved outside the rust official docs but my understanding is Cargo.lock shouldn't ever be included in a pure library package.

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

It's a bit confusing to have it there.

**Comment by mainrs** [comment]
It's still a topic where different people have different opinions. But recently an official blog post changed the recommended approach:

https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html

**Comment by SpamapS** [comment]
TIL! Thanks for the pointer.

**Comment by matthiasbeyer** [comment]
I'll close this as the public guideline now is to check them into the repository.
Either way: Thanks for you contributions! :laughing:

**Comment by epage** [comment]
Note that we had our `Cargo.lock` before that policy change.   Several of us maintainers checking in `Cargo.lock` helped inform things when I advocated that policy change and then wrote that blog post.
