### ISSUE TITLE
Missing changelog for 0.10.1

### ISSUE THREAD

**Issue by msrd0** [rust-cli/env_logger#293]
Something doesn't seem right ...

![image](https://github.com/rust-cli/env_logger/assets/7853372/67663c5e-e573-44ed-86cd-209700dfe7b4)

[CHANGELOG.md](https://github.com/rust-cli/env_logger/blob/3e48a157cad69d17e601400390e1339d57b664c6/CHANGELOG.md)

**Comment by epage** [comment]
I've gone ahead and put some things in
- Most changes were updating the structure of the project itself
- There was a `be be` typo in docs
- There was a speculative performance improvement
- There was some clean up of `RUST_LOG` docs

Of those, `RUST_LOG` is the most notable and that still isn't much.  Sometimes, things are small enough that they just aren't worth having an entry.  Maybe I should least note that.
