### ISSUE TITLE
Feature Deprecation Without Warning or Migration

### ISSUE THREAD

**Issue by TylerJMcLean** [rust-cli/env_logger#309]
The [color] feature was removed in 0.11 with (from what I can see) no explanation as to why, and no deprecation warnings that would suggest this was coming.

- Why was this feature removed?
- What (if any) is the migration pathway exists for users of this feature?

**Comment by epage** [comment]
What do you mean by "[color] feature".

The Cargo.toml feature `color` is still present.

If you mean the bespoke formatting API under `fmt`, you do have to read a little between the lines in the [changelog](https://github.com/rust-cli/env_logger/blob/main/CHANGELOG.md#0110---2024-01-19).  That could be more clear.

The key feature is

> Automatically adapt ANSI escape codes in logged messages to the current terminal's capabilities

You are now free to use whatever styling API you want to generate ANSI styled strings and pass them to `env_logger`.  `env_logger` will adapt them to the current system as needed, even to the legacy wincon API.

**Comment by epage** [comment]
Created #310 to fill some API gaps

**Comment by TylerJMcLean** [comment]
Hey @epage, yeah I should have been more specific on versioning when I wrote this. I noticed between 10.2->11.0 color code had been removed and though the `color` feature had appeared to be restored in 11.1, there was no bespoke mention of how one using the previous API could update their code. #310 covers exactly what I'm looking for. Thank you for your speedy response!
