### ISSUE TITLE
Support for filename and line number

### ISSUE THREAD

**Issue by EriKWDev** [rust-cli/env_logger#344]
The `log::Record` contains information about the filename and line number the log comes from which I have found is very useful during development.

It would be nice if it could be enabled optionally similarly to how timestamps can be turned off and module paths can be turned on.

I have a custom format-fn at the moment to do this but it would be neat if it was built-in since all other coloring and stuff is still very useful.

```log
[ LEVEL crate path/to/file.rs:1337 ]
```

**Comment by epage** [comment]
prior art: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Format.html#method.with_file (and `with_line_number` and `with_source_location`)

**Comment by EriKWDev** [comment]
and apparently #232
